    ENCODER_CCW_CW(KC_LEFT, KC_RIGHT),
    ENCODER_CCW_CW(KC_LEFT, KC_RIGHT),
    ENCODER_CCW_CW(KC_LEFT, KC_RIGHT),
    ENCODER_CCW_CW(KC_VOLD, KC_VOLU),
    ENCODER_CCW_CW(KC_PGUP, KC_PGDN),
    ENCODER_CCW_CW(KC_PGUP, KC_PGDN),
    ENCODER_CCW_CW(KC_PGUP, KC_PGDN),
    ENCODER_CCW_CW(KC_VOLD, KC_VOLU)
